;;; Print a paste-ready replacement for tests/r7rs/expected.scm.
;;;
;;; Run after every fix (`make r7rs-baseline`), paste over expected.scm, and
;;; READ THE DIFF — that diff is the proof the fix did what it claimed, and the
;;; only place a regression elsewhere in the suite shows up.

(import (scheme base) (scheme write) (paal-r7rs-driver))

(define result
  (run-r7rs-suite! "tests/r7rs/r7rs-tests.scm" "tests/r7rs/libs" '()))

(newline)
(display ";;; Generated by `make r7rs-baseline`.  Do not hand-edit -- regenerate.\n")
(display ";;; See tests/r7rs/README.md.\n\n")
(display "(define-library (paal-r7rs-expected)\n")
(display "  (export expected-sections expected-errors)\n")
(display "  (begin\n\n")
(display "    ;; (section-name passing failing) per test-end, in suite order.\n")
(display "    (define expected-sections\n      '(")
(let loop ((ss (r7rs-sections result)) (first #t))
  (unless (null? ss)
    (unless first (display "\n        "))
    (write (car ss))
    (loop (cdr ss) #f)))
(display "))\n\n")
(display "    ;; Top-level forms that raise before any test inside them runs.\n")
(display "    (define expected-errors\n      '")
(write (r7rs-errors result))
(display ")))\n")
