;;; Generated by `make r7rs-baseline`.  Do not hand-edit -- regenerate.
;;; See tests/r7rs/README.md.

(define-library (paal-r7rs-expected)
  (export expected-sections expected-errors)
  (begin

    ;; (section-name passing failing) per test-end, in suite order.
    (define expected-sections
      '(("R7RS" 0 0)
        ("4.1 Primitive expression types" 27 0)
        ("4.2 Derived expression types" 74 0)
        ("4.3 Macros" 20 5)
        ("5 Program structure" 15 0)
        ("6.1 Equivalence Predicates" 25 0)
        ("6.2 Numbers" 210 1)
        ("6.3 Booleans" 18 0)
        ("6.4 Lists" 65 0)
        ("6.5 Symbols" 17 0)
        ("6.6 Characters" 79 0)
        ("6.7 Strings" 130 0)
        ("6.8 Vectors" 43 0)
        ("6.9 Bytevectors" 39 0)
        ("6.10 Control Features" 34 0)
        ("6.11 Exceptions" 30 0)
        ("6.12 Environments and evaluation" 4 0)
        ("6.13 Input and output" 63 0)
        ("Read syntax" 93 0)
        ("Numeric syntax" 220 0)
        ("6.14 System interface" 13 0)))

    ;; Top-level forms that raise before any test inside them runs.
    (define expected-errors
      '())))
