KAAPPI      ?= kaappi
KAAPPI_SRC  ?= ../kaappi
LIB          = lib
KAAPPI_TEST ?= ../kaappi-test/lib

LIBS = --lib-path $(LIB) --lib-path $(KAAPPI_TEST)
# The R7RS harness resolves (paal-r7rs-driver) and (paal-r7rs-expected) from
# tests/r7rs; the suite itself resolves (chibi test) from tests/r7rs/libs, which
# paal's own expander searches, not this one.
R7RS_LIBS = $(LIBS) --lib-path tests/r7rs

.PHONY: all test test-unit test-r7rs r7rs-baseline coverage run binary check-binary pbc-pipeline embed-srfi clean-cache clean

# Bare `make` builds the binary.  That needs the kaappi *source* checkout and
# zig, not just a kaappi on PATH — `make test` is the target that runs against
# the interpreter alone, and is what CI calls.
all: binary

test: test-unit test-r7rs

test-unit:
	$(KAAPPI) --coverage-xml coverage.xml $(LIBS) tests/test-paal.scm

# R7RS conformance, asserted against a recorded baseline — a ratchet, not a
# gate.  See tests/r7rs/README.md.
test-r7rs:
	$(KAAPPI) $(R7RS_LIBS) tests/test-r7rs.scm

# Print a replacement baseline.  Redirect over tests/r7rs/paal-r7rs-expected.sld
# and read the diff — that diff is the evidence a fix worked.
r7rs-baseline:
	@$(KAAPPI) $(R7RS_LIBS) tests/r7rs/baseline.scm 2>/dev/null | sed -n '/Generated by/,$$p'

coverage:
	$(KAAPPI) --coverage $(LIBS) tests/test-paal.scm

# Run paal via the bootstrap interpreter (no build step needed).
# Usage: make run ARGS="run file.scm"  or  make run ARGS="eval '(+ 1 2)'"
run:
	$(KAAPPI) $(LIBS) src/main.scm $(ARGS)

# Build a standalone paal binary (requires kaappi source + zig).
# Override KAAPPI_SRC if the kaappi repo is not at ../kaappi.
#
# Two-step process:
#   1. Build kaappi from source (if not already built).
#   2. Compile main.scm to bytecode using that binary (so format versions match).
#   3. Bundle the bytecode into the final binary.
KAAPPI_BIN = $(KAAPPI_SRC)/zig-out/bin/kaappi

binary: src/main.scm
	# Fail early if the embedded SRFI sources are stale, rather than shipping
	# a binary whose bundled libraries differ from lib/srfi/.
	python3 tools/embed-srfi.py
	# Build plain kaappi first so KAAPPI_BIN is not a previous bundled paal.
	# zig caches aggressively, so this is fast if nothing changed.
	cd $(KAAPPI_SRC) && zig build
	$(KAAPPI_BIN) --compile $(LIBS) src/main.scm -o paal.sbc
	cd $(KAAPPI_SRC) && zig build -Dbundle=$(CURDIR)/paal.sbc
	cp $(KAAPPI_SRC)/zig-out/bin/kaappi paal
	rm -f paal.sbc
	# Leave the kaappi checkout as we found it.  -Dbundle overwrites
	# zig-out/bin/kaappi in place, so without this the kaappi repo is left
	# holding a paal binary that still answers --version as kaappi -- it only
	# gives itself away when you run it with no arguments and get paal's REPL.
	cd $(KAAPPI_SRC) && zig build
	@echo "Built: paal"

# Smoke-test the built binary.
check-binary: paal
	./paal version
	./paal eval '(+ 1 2)'
	./paal eval '(define (fact n) (if (= n 0) 1 (* n (fact (- n 1))))) (fact 5)'

# Regenerate the embedded SRFI sources compiled into the binary.  Run after
# changing anything under lib/srfi/; the result is committed.
embed-srfi:
	python3 tools/embed-srfi.py

# Build the pipeline bytecode cache (speeds up self-hosted run/compile).
# Run once after checkout, and again whenever a paal library file changes.
pbc-pipeline:
	@mkdir -p cache
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/ir.sld        -o cache/paal-ir.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/bytecode.sld  -o cache/paal-bytecode.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/reader.sld    -o cache/paal-reader.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/expander.sld  -o cache/paal-expander.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/compiler.sld  -o cache/paal-compiler.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/frame.sld     -o cache/paal-frame.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/emitter.sld   -o cache/paal-emitter.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/vm-bc.sld     -o cache/paal-vm-bc.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/serializer.sld -o cache/paal-serializer.pbc
	@echo "Pipeline cache built in cache/"

clean-cache:
	rm -f cache/*.pbc
	@echo "Cache cleared"

clean:
	rm -f coverage.xml paal
