KAAPPI      ?= kaappi
LIB          = lib

# The sibling repos are found from the main checkout, not from the current
# directory.  In a git worktree `..` points inside the worktree tree rather than
# at the workspace root, so a plain ../kaappi-test/lib resolved to nothing, every
# --lib-path miss was ignored silently, and the suite then failed ~700 times with
# `undefined variable` -- reading as though paal itself were broken.  See #3.
#
# --git-common-dir names the *main* checkout's .git from inside a worktree;
# --path-format=absolute because the bare flag answers a relative ".git" when run
# from the main checkout.  If git is missing or this is a tarball, dirname of the
# empty string is ".", which reproduces the old relative behaviour exactly.
PAAL_ROOT   := $(shell dirname "$$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)" 2>/dev/null || echo .)
KAAPPI_SRC  ?= $(PAAL_ROOT)/../kaappi
KAAPPI_TEST ?= $(PAAL_ROOT)/../kaappi-test/lib

LIBS = --lib-path $(LIB) --lib-path $(KAAPPI_TEST)
# The R7RS harness resolves (paal-r7rs-driver) and (paal-r7rs-expected) from
# tests/r7rs; the suite itself resolves (chibi test) from tests/r7rs/libs, which
# paal's own expander searches, not this one.
R7RS_LIBS = $(LIBS) --lib-path tests/r7rs

.PHONY: all test test-unit test-r7rs r7rs-baseline coverage check-test-deps run binary check-binary pbc-pipeline embed-srfi clean-cache clean

# One clear line instead of ~700.  A --lib-path that does not exist is ignored
# silently, so a wrong KAAPPI_TEST does not fail here -- it fails once per
# assertion, as `undefined variable 'test-equal'`, which reads like paal is
# broken rather than like a path is wrong.  Only the targets that resolve
# (kaappi test) need this: `run` and `binary` never look inside KAAPPI_TEST.
check-test-deps:
	@test -d "$(KAAPPI_TEST)" || { \
	  echo "error: (kaappi test) not found at $(KAAPPI_TEST)"; \
	  echo "       expected the kaappi-test repo beside this one; override with"; \
	  echo "       make $(MAKECMDGOALS) KAAPPI_TEST=/path/to/kaappi-test/lib"; \
	  exit 1; }

# Bare `make` builds the binary.  That needs the kaappi *source* checkout and
# zig, not just a kaappi on PATH — `make test` is the target that runs against
# the interpreter alone, and is what CI calls.
all: binary

test: test-unit test-r7rs

test-unit: check-test-deps
	$(KAAPPI) --coverage-xml coverage.xml $(LIBS) tests/test-paal.scm

# R7RS conformance, asserted against a recorded baseline — a ratchet, not a
# gate.  See tests/r7rs/README.md.
test-r7rs: check-test-deps
	$(KAAPPI) $(R7RS_LIBS) tests/test-r7rs.scm

# Print a replacement baseline.  Redirect over tests/r7rs/paal-r7rs-expected.sld
# and read the diff — that diff is the evidence a fix worked.
r7rs-baseline: check-test-deps
	@$(KAAPPI) $(R7RS_LIBS) tests/r7rs/baseline.scm 2>/dev/null | sed -n '/Generated by/,$$p'

coverage: check-test-deps
	$(KAAPPI) --coverage $(LIBS) tests/test-paal.scm

# Run paal via the bootstrap interpreter (no build step needed).
# Usage: make run ARGS="run file.scm"  or  make run ARGS="eval '(+ 1 2)'"
run:
	$(KAAPPI) $(LIBS) src/main.scm $(ARGS)

# Build a standalone paal binary (requires kaappi source + zig).
# Override KAAPPI_SRC if the kaappi repo is not at ../kaappi.
#
# Two-step process:
#   1. Build kaappi from source (if not already built).
#   2. Compile main.scm to bytecode using that binary (so format versions match).
#   3. Bundle the bytecode into the final binary.
KAAPPI_BIN = $(KAAPPI_SRC)/zig-out/bin/kaappi

binary: src/main.scm
	# Fail early if the embedded SRFI sources are stale, rather than shipping
	# a binary whose bundled libraries differ from lib/srfi/.
	python3 tools/embed-srfi.py
	# Build plain kaappi first so KAAPPI_BIN is not a previous bundled paal.
	# zig caches aggressively, so this is fast if nothing changed.
	cd $(KAAPPI_SRC) && zig build
	$(KAAPPI_BIN) --compile $(LIBS) src/main.scm -o paal.sbc
	cd $(KAAPPI_SRC) && zig build -Dbundle=$(CURDIR)/paal.sbc
	cp $(KAAPPI_SRC)/zig-out/bin/kaappi paal
	rm -f paal.sbc
	# Leave the kaappi checkout as we found it.  -Dbundle overwrites
	# zig-out/bin/kaappi in place, so without this the kaappi repo is left
	# holding a paal binary that still answers --version as kaappi -- it only
	# gives itself away when you run it with no arguments and get paal's REPL.
	cd $(KAAPPI_SRC) && zig build
	@echo "Built: paal"

# Smoke-test the built binary.
check-binary: paal
	./paal version
	./paal eval '(+ 1 2)'
	./paal eval '(define (fact n) (if (= n 0) 1 (* n (fact (- n 1))))) (fact 5)'

# Regenerate the embedded SRFI sources compiled into the binary.  Run after
# changing anything under lib/srfi/; the result is committed.
embed-srfi:
	python3 tools/embed-srfi.py

# Build the pipeline bytecode cache (speeds up self-hosted run/compile).
# Run once after checkout, and again whenever a paal library file changes.
pbc-pipeline:
	@mkdir -p cache
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/ir.sld        -o cache/paal-ir.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/bytecode.sld  -o cache/paal-bytecode.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/reader.sld    -o cache/paal-reader.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/expander.sld  -o cache/paal-expander.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/compiler.sld  -o cache/paal-compiler.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/frame.sld     -o cache/paal-frame.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/emitter.sld   -o cache/paal-emitter.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/vm-bc.sld     -o cache/paal-vm-bc.pbc
	$(KAAPPI) $(LIBS) src/main.scm compile lib/kaappi/paal/serializer.sld -o cache/paal-serializer.pbc
	@echo "Pipeline cache built in cache/"

clean-cache:
	rm -f cache/*.pbc
	@echo "Cache cleared"

clean:
	rm -f coverage.xml paal
