;;; (kaappi paal embedded) — libraries compiled into the binary
;;;
;;; A standalone `paal` reads library .sld files from disk, so a binary run
;;; outside the repo cannot resolve (import (srfi 1)).  This table holds the
;;; source of the bundled libraries so the expander can find them with no
;;; filesystem at all.
;;;
;;; Regenerated by `make embed-srfi`, which rewrites everything between the
;;; markers below.  It is committed rather than generated at build time so a
;;; fresh checkout builds without the generator having run, and so the diff
;;; shows when a bundled library changes.
;;;
;;; Entries are (name . source-text).  The expander consults this before
;;; searching the library path, so a file on disk cannot shadow a bundled
;;; library — that would make a binary's behaviour depend on its working
;;; directory, which is the thing bundling exists to avoid.

(define-library (kaappi paal embedded)
  (import (scheme base))
  (export paal-embedded-source)
  (begin

    ;; BEGIN GENERATED — do not edit by hand
    (define %paal-embedded
      (list
       (cons '(srfi 1)
             ";;; SRFI 1 — List Library
;;;
;;; The commonly-used subset, written in portable R7RS so it runs on paal and
;;; on kaappi unchanged.  Procedures R7RS already provides under the same name
;;; and semantics (`map`, `for-each`, `length`, `append`, `reverse`,
;;; `list-tail`, `list-ref`, `member`, `assoc`, `list-copy`) are deliberately
;;; not redefined: importing this library alongside `(scheme base)` would then
;;; bind one name two ways, which R7RS 5.2 makes an error.
;;;
;;; Not implemented: the linear-update (`!`) variants, circular-list support,
;;; `list-index` on multiple lists, and the comparator-taking set operations
;;; beyond the basic four.

(define-library (srfi 1)
  (import (scheme base))
  (export
    ;; constructors
    xcons cons* make-list list-tabulate iota circular-list
    ;; predicates
    proper-list? circular-list? dotted-list? null-list? not-pair?
    list=
    ;; selectors
    first second third fourth fifth sixth seventh eighth ninth tenth
    car+cdr take drop take-right drop-right last last-pair
    split-at
    ;; miscellaneous
    zip unzip1 unzip2 concatenate append-reverse length+
    ;; folds and friends
    fold fold-right reduce reduce-right append-map filter-map
    unfold unfold-right
    pair-fold pair-fold-right pair-for-each map-in-order
    ;; filtering and searching
    filter remove partition find find-tail any every list-index
    take-while drop-while span break count
    delete delete-duplicates
    ;; association lists
    alist-copy alist-cons alist-delete del-assq del-assv del-assoc
    ;; sets over lists
    lset-adjoin lset-union lset-intersection lset-difference
    lset= lset-xor)
  (begin

    ;; --- constructors ------------------------------------------------

    (define (xcons d a) (cons a d))

    (define (cons* first . rest)
      (let recur ((x first) (rest rest))
        (if (null? rest)
            x
            (cons x (recur (car rest) (cdr rest))))))

    (define (list-tabulate n proc)
      (let loop ((i (- n 1)) (acc '()))
        (if (< i 0) acc (loop (- i 1) (cons (proc i) acc)))))

    ;; (iota count [start [step]])
    (define (iota count . rest)
      (let ((start (if (pair? rest) (car rest) 0))
            (step  (if (and (pair? rest) (pair? (cdr rest))) (cadr rest) 1)))
        (let loop ((i (- count 1)) (acc '()))
          (if (< i 0)
              acc
              (loop (- i 1) (cons (+ start (* i step)) acc))))))

    ;; The one SRFI 1 constructor whose result is deliberately cyclic.  At
    ;; least one element, or there is no pair to close the knot through.
    (define (circular-list first . rest)
      (let ((l (cons first rest)))
        (set-cdr! (last-pair l) l)
        l))

    ;; --- predicates --------------------------------------------------

    ;; Walks with two pointers so a circular list terminates rather than
    ;; hanging: the fast pointer laps the slow one exactly when there is a
    ;; cycle.  proper-list? and dotted-list? need the same walk.
    (define (%classify x)
      ;; 'proper, 'circular or 'dotted
      (let loop ((slow x) (fast x) (first? #t))
        (cond
          ((null? fast) 'proper)
          ((not (pair? fast)) 'dotted)
          ((null? (cdr fast)) 'proper)
          ((not (pair? (cdr fast))) 'dotted)
          ((and (not first?) (eq? slow fast)) 'circular)
          (else (loop (cdr slow) (cddr fast) #f)))))

    (define (proper-list? x)   (eq? (%classify x) 'proper))
    (define (circular-list? x) (eq? (%classify x) 'circular))
    (define (dotted-list? x)   (eq? (%classify x) 'dotted))

    (define (null-list? x)
      (cond ((null? x) #t)
            ((pair? x) #f)
            (else (error \"null-list?: argument is neither null nor a pair\" x))))

    (define (not-pair? x) (not (pair? x)))

    (define (list= elt= . lists)
      (cond
        ((null? lists) #t)
        ((null? (cdr lists)) #t)
        (else
         (let outer ((a (car lists)) (rest (cdr lists)))
           (if (null? rest)
               #t
               (let ((b (car rest)))
                 (and (let inner ((x a) (y b))
                        (cond ((null? x) (null? y))
                              ((null? y) #f)
                              ((elt= (car x) (car y)) (inner (cdr x) (cdr y)))
                              (else #f)))
                      (outer b (cdr rest)))))))))

    ;; --- selectors ---------------------------------------------------

    (define (first x)   (car x))
    (define (second x)  (cadr x))
    (define (third x)   (caddr x))
    (define (fourth x)  (cadddr x))
    (define (fifth x)   (list-ref x 4))
    (define (sixth x)   (list-ref x 5))
    (define (seventh x) (list-ref x 6))
    (define (eighth x)  (list-ref x 7))
    (define (ninth x)   (list-ref x 8))
    (define (tenth x)   (list-ref x 9))

    (define (car+cdr p) (values (car p) (cdr p)))

    (define (take lst k)
      (let loop ((l lst) (k k) (acc '()))
        (if (= k 0)
            (reverse acc)
            (loop (cdr l) (- k 1) (cons (car l) acc)))))

    (define (drop lst k)
      (let loop ((l lst) (k k))
        (if (= k 0) l (loop (cdr l) (- k 1)))))

    ;; Advance a second pointer k ahead, then walk both to the end.
    (define (take-right lst k)
      (let loop ((lag lst) (lead (drop lst k)))
        (if (pair? lead) (loop (cdr lag) (cdr lead)) lag)))

    (define (drop-right lst k)
      (let loop ((lag lst) (lead (drop lst k)) (acc '()))
        (if (pair? lead)
            (loop (cdr lag) (cdr lead) (cons (car lag) acc))
            (reverse acc))))

    (define (last-pair lst)
      (let loop ((l lst))
        (if (pair? (cdr l)) (loop (cdr l)) l)))

    (define (last lst) (car (last-pair lst)))

    ;; (values (take lst n) (drop lst n)) in one pass over the prefix.
    (define (split-at lst n)
      (let loop ((l lst) (k n) (acc '()))
        (if (= k 0)
            (values (reverse acc) l)
            (loop (cdr l) (- k 1) (cons (car l) acc)))))

    ;; --- miscellaneous -----------------------------------------------

    (define (zip . lists) (apply map list lists))

    (define (unzip1 lst) (map car lst))

    (define (unzip2 lst)
      (values (map car lst) (map cadr lst)))

    (define (concatenate lists) (apply append lists))

    (define (append-reverse rev tail)
      (let loop ((l rev) (acc tail))
        (if (null? l) acc (loop (cdr l) (cons (car l) acc)))))

    ;; length, except a circular list answers #f and a dotted list its pair
    ;; count is not needed — SRFI 1 leaves dotted lists to `length`'s error.
    ;; Same two-pointer walk the predicates use.
    (define (length+ lst)
      (let loop ((slow lst) (fast lst) (n 0))
        (cond ((null? fast) n)
              ((not (pair? fast)) (error \"length+: not a proper or circular list\" lst))
              ((null? (cdr fast)) (+ n 1))
              ((eq? (cdr fast) slow) #f)
              (else (loop (cdr slow) (cddr fast) (+ n 2))))))

    ;; --- folds -------------------------------------------------------

    (define (fold kons knil lst . rest)
      (if (null? rest)
          (let loop ((l lst) (acc knil))
            (if (null? l) acc (loop (cdr l) (kons (car l) acc))))
          (let loop ((ls (cons lst rest)) (acc knil))
            (if (%any-null? ls)
                acc
                (loop (map cdr ls) (apply kons (append (map car ls) (list acc))))))))

    (define (fold-right kons knil lst . rest)
      (if (null? rest)
          (let loop ((l lst))
            (if (null? l) knil (kons (car l) (loop (cdr l)))))
          (let loop ((ls (cons lst rest)))
            (if (%any-null? ls)
                knil
                (apply kons (append (map car ls) (list (loop (map cdr ls)))))))))

    (define (%any-null? ls)
      (cond ((null? ls) #f)
            ((null? (car ls)) #t)
            (else (%any-null? (cdr ls)))))

    (define (reduce f ridentity lst)
      (if (null? lst) ridentity (fold f (car lst) (cdr lst))))

    (define (reduce-right f ridentity lst)
      (if (null? lst)
          ridentity
          (let loop ((l lst))
            (if (null? (cdr l))
                (car l)
                (f (car l) (loop (cdr l)))))))

    (define (append-map f lst . rest)
      (apply append (apply map f lst rest)))

    (define (filter-map f lst . rest)
      (let loop ((l (apply map f lst rest)) (acc '()))
        (cond ((null? l) (reverse acc))
              ((car l) (loop (cdr l) (cons (car l) acc)))
              (else (loop (cdr l) acc)))))

    ;; (unfold p f g seed) — p says when to stop, f maps, g steps.
    (define (unfold p f g seed)
      (let loop ((seed seed) (acc '()))
        (if (p seed)
            (reverse acc)
            (loop (g seed) (cons (f seed) acc)))))

    (define (unfold-right p f g seed)
      (let loop ((seed seed) (acc '()))
        (if (p seed) acc (loop (g seed) (cons (f seed) acc)))))

    ;; The pair-walking folds see each successive pair, not each element.
    ;; The cdr is taken before kons runs, so a kons that set-cdr!s the pair
    ;; it was handed — SRFI 1's own destructive-reverse example — does not
    ;; derail the walk.
    (define (pair-fold kons knil lst)
      (let loop ((l lst) (acc knil))
        (if (pair? l)
            (let ((tail (cdr l)))
              (loop tail (kons l acc)))
            acc)))

    (define (pair-fold-right kons knil lst)
      (let loop ((l lst))
        (if (pair? l)
            (kons l (loop (cdr l)))
            knil)))

    (define (pair-for-each proc lst)
      (let loop ((l lst))
        (when (pair? l)
          (let ((tail (cdr l)))
            (proc l)
            (loop tail)))))

    ;; map with the application order guaranteed left to right.  paal's map
    ;; happens to walk that way, but the guarantee is this name's whole
    ;; contract, so it gets its own loop rather than an alias.
    (define (map-in-order f lst . rest)
      (if (null? rest)
          (let loop ((l lst) (acc '()))
            (if (null? l)
                (reverse acc)
                (let ((v (f (car l))))
                  (loop (cdr l) (cons v acc)))))
          (let loop ((ls (cons lst rest)) (acc '()))
            (if (let scan ((ls ls)) (and (pair? ls) (or (null? (car ls)) (scan (cdr ls)))))
                (reverse acc)
                (let ((v (apply f (map car ls))))
                  (loop (map cdr ls) (cons v acc)))))))

    ;; --- filtering and searching -------------------------------------

    (define (filter pred lst)
      (let loop ((l lst) (acc '()))
        (cond ((null? l) (reverse acc))
              ((pred (car l)) (loop (cdr l) (cons (car l) acc)))
              (else (loop (cdr l) acc)))))

    (define (remove pred lst)
      (filter (lambda (x) (not (pred x))) lst))

    (define (partition pred lst)
      (let loop ((l lst) (yes '()) (no '()))
        (cond ((null? l) (values (reverse yes) (reverse no)))
              ((pred (car l)) (loop (cdr l) (cons (car l) yes) no))
              (else (loop (cdr l) yes (cons (car l) no))))))

    (define (find pred lst)
      (let ((tail (find-tail pred lst)))
        (and tail (car tail))))

    (define (find-tail pred lst)
      (let loop ((l lst))
        (cond ((null? l) #f)
              ((pred (car l)) l)
              (else (loop (cdr l))))))

    ;; Returns the last application's value, not just #t, per SRFI 1.
    (define (any pred lst . rest)
      (if (null? rest)
          (let loop ((l lst))
            (cond ((null? l) #f)
                  ((pred (car l)))
                  (else (loop (cdr l)))))
          (let loop ((ls (cons lst rest)))
            (cond ((%any-null? ls) #f)
                  ((apply pred (map car ls)))
                  (else (loop (map cdr ls)))))))

    (define (every pred lst . rest)
      (if (null? rest)
          (let loop ((l lst) (last #t))
            (cond ((null? l) last)
                  ((pred (car l)) => (lambda (v) (loop (cdr l) v)))
                  (else #f)))
          (let loop ((ls (cons lst rest)) (last #t))
            (cond ((%any-null? ls) last)
                  ((apply pred (map car ls)) => (lambda (v) (loop (map cdr ls) v)))
                  (else #f)))))

    (define (list-index pred lst)
      (let loop ((l lst) (i 0))
        (cond ((null? l) #f)
              ((pred (car l)) i)
              (else (loop (cdr l) (+ i 1))))))

    (define (take-while pred lst)
      (let loop ((l lst) (acc '()))
        (if (or (null? l) (not (pred (car l))))
            (reverse acc)
            (loop (cdr l) (cons (car l) acc)))))

    (define (drop-while pred lst)
      (let loop ((l lst))
        (if (or (null? l) (not (pred (car l)))) l (loop (cdr l)))))

    (define (span pred lst)
      (values (take-while pred lst) (drop-while pred lst)))

    (define (break pred lst)
      (span (lambda (x) (not (pred x))) lst))

    (define (count pred lst)
      (let loop ((l lst) (n 0))
        (cond ((null? l) n)
              ((pred (car l)) (loop (cdr l) (+ n 1)))
              (else (loop (cdr l) n)))))

    ;; (delete x lst [=]) — equal? by default
    (define (delete x lst . rest)
      (let ((elt= (if (pair? rest) (car rest) equal?)))
        (filter (lambda (y) (not (elt= x y))) lst)))

    (define (delete-duplicates lst . rest)
      (let ((elt= (if (pair? rest) (car rest) equal?)))
        (let loop ((l lst) (acc '()))
          (cond ((null? l) (reverse acc))
                ((%member? (car l) acc elt=) (loop (cdr l) acc))
                (else (loop (cdr l) (cons (car l) acc)))))))

    (define (%member? x lst elt=)
      (cond ((null? lst) #f)
            ((elt= x (car lst)) #t)
            (else (%member? x (cdr lst) elt=))))

    ;; --- association lists -------------------------------------------

    (define (alist-copy alist)
      (map (lambda (p) (cons (car p) (cdr p))) alist))

    (define (alist-cons key datum alist)
      (cons (cons key datum) alist))

    ;; The optional comparison defaults to equal?, and the key is its first
    ;; argument, per SRFI 1 — (= key entry-key).
    (define (alist-delete key alist . rest)
      (let ((same? (if (pair? rest) (car rest) equal?)))
        (filter (lambda (p) (not (same? key (car p)))) alist)))

    (define (%del-as key alist same?)
      (filter (lambda (p) (not (same? key (car p)))) alist))

    (define (del-assq key alist)  (%del-as key alist eq?))
    (define (del-assv key alist)  (%del-as key alist eqv?))
    (define (del-assoc key alist) (%del-as key alist equal?))

    ;; --- sets over lists ---------------------------------------------

    (define (lset-adjoin elt= lst . elts)
      (fold (lambda (e acc)
              (if (%member? e acc elt=) acc (append acc (list e))))
            lst elts))

    (define (lset-union elt= . lists)
      (if (null? lists)
          '()
          (fold (lambda (l acc)
                  (fold (lambda (e acc)
                          (if (%member? e acc elt=) acc (append acc (list e))))
                        acc l))
                (car lists) (cdr lists))))

    (define (lset-intersection elt= lst . rest)
      (filter (lambda (e)
                (let loop ((ls rest))
                  (cond ((null? ls) #t)
                        ((%member? e (car ls) elt=) (loop (cdr ls)))
                        (else #f))))
              lst))

    (define (lset-difference elt= lst . rest)
      (filter (lambda (e)
                (let loop ((ls rest))
                  (cond ((null? ls) #t)
                        ((%member? e (car ls) elt=) #f)
                        (else (loop (cdr ls))))))
              lst))

    ;; Set equality is mutual containment; chained across the arguments the
    ;; way = chains across numbers.  No arguments or one argument is #t.
    (define (lset= elt= . lists)
      (let ((subset? (lambda (a b)
                       (let loop ((l a))
                         (cond ((null? l) #t)
                               ((%member? (car l) b elt=) (loop (cdr l)))
                               (else #f))))))
        (let loop ((ls lists))
          (cond ((null? ls) #t)
                ((null? (cdr ls)) #t)
                ((and (subset? (car ls) (cadr ls))
                      (subset? (cadr ls) (car ls)))
                 (loop (cdr ls)))
                (else #f)))))

    ;; Symmetric difference, folded pairwise across the arguments.
    (define (lset-xor elt= . lists)
      (let ((xor2 (lambda (a b)
                    (append (filter (lambda (e) (not (%member? e b elt=))) a)
                            (filter (lambda (e) (not (%member? e a elt=))) b)))))
        (if (null? lists)
            '()
            (let loop ((acc (car lists)) (ls (cdr lists)))
              (if (null? ls)
                  acc
                  (loop (xor2 acc (car ls)) (cdr ls)))))))))
")
       (cons '(srfi 9)
             ";;; SRFI 9 — Defining Record Types
;;;
;;; define-record-type is a core form in paal's expander (it desugars to
;;; tagged vectors), so this library exists only to give the SRFI its import
;;; path.  Importing it is a no-op that succeeds.
(define-library (srfi 9)
  (export)
  (begin))
")
       (cons '(srfi 13)
             ";;; SRFI 13 — String Library
;;;
;;; The commonly-used subset.  Names R7RS already binds compatibly
;;; (`string-copy`, `string-append`, `string-length`, `string-ref`,
;;; `string=?` and the other comparisons, `string-upcase`/`downcase`) are not
;;; redefined — importing this alongside `(scheme base)` would otherwise bind
;;; one name two ways, which R7RS 5.2 makes an error.
;;;
;;; SRFI 13's optional start/end arguments are supported on the procedures
;;; where they carry their weight; the full every-procedure treatment, the
;;; `!` linear-update variants, and the char-set arguments (which need SRFI
;;; 14) are not implemented.

(define-library (srfi 13)
  (import (scheme base) (scheme char))
  (export
    string-null? string-every string-any
    string-take string-drop string-take-right string-drop-right
    string-pad string-pad-right
    string-trim string-trim-right string-trim-both
    string-prefix? string-suffix?
    string-index string-index-right string-rindex
    string-skip string-skip-right
    string-contains string-count
    string-join string-split string-tokenize
    string-reverse string-concatenate
    string-fold string-fold-right
    string-unfold string-unfold-right
    string-tabulate string-titlecase
    string-delete string-filter string-replace)
  (begin

    (define (string-null? s) (= (string-length s) 0))

    (define (string-every pred s)
      (let loop ((i 0) (last #t))
        (cond ((= i (string-length s)) last)
              ((pred (string-ref s i)) => (lambda (v) (loop (+ i 1) v)))
              (else #f))))

    (define (string-any pred s)
      (let loop ((i 0))
        (cond ((= i (string-length s)) #f)
              ((pred (string-ref s i)))
              (else (loop (+ i 1))))))

    (define (string-take s n)       (substring s 0 n))
    (define (string-drop s n)       (substring s n (string-length s)))
    (define (string-take-right s n) (substring s (- (string-length s) n)
                                               (string-length s)))
    (define (string-drop-right s n) (substring s 0 (- (string-length s) n)))

    ;; Longer than len keeps the *rightmost* len characters, per SRFI 13.
    (define (string-pad s len . rest)
      (let ((c (if (pair? rest) (car rest) #\\space))
            (n (string-length s)))
        (if (>= n len)
            (substring s (- n len) n)
            (string-append (make-string (- len n) c) s))))

    (define (string-pad-right s len . rest)
      (let ((c (if (pair? rest) (car rest) #\\space))
            (n (string-length s)))
        (if (>= n len)
            (substring s 0 len)
            (string-append s (make-string (- len n) c)))))

    (define (%trim-pred rest)
      (if (pair? rest) (car rest) char-whitespace?))

    (define (string-trim s . rest)
      (let ((pred (%trim-pred rest)) (n (string-length s)))
        (let loop ((i 0))
          (cond ((= i n) \"\")
                ((pred (string-ref s i)) (loop (+ i 1)))
                (else (substring s i n))))))

    (define (string-trim-right s . rest)
      (let ((pred (%trim-pred rest)))
        (let loop ((i (string-length s)))
          (cond ((= i 0) \"\")
                ((pred (string-ref s (- i 1))) (loop (- i 1)))
                (else (substring s 0 i))))))

    (define (string-trim-both s . rest)
      (apply string-trim (apply string-trim-right s rest) rest))

    (define (string-prefix? prefix s)
      (let ((np (string-length prefix)))
        (and (<= np (string-length s))
             (string=? prefix (substring s 0 np)))))

    (define (string-suffix? suffix s)
      (let ((ns (string-length suffix)) (n (string-length s)))
        (and (<= ns n)
             (string=? suffix (substring s (- n ns) n)))))

    ;; SRFI 13 takes a char/predicate; both are accepted here.
    (define (%char-match pred)
      (if (char? pred) (lambda (c) (char=? c pred)) pred))

    (define (string-index s pred . rest)
      (let ((match (%char-match pred))
            (start (if (pair? rest) (car rest) 0))
            (end   (if (and (pair? rest) (pair? (cdr rest)))
                       (cadr rest) (string-length s))))
        (let loop ((i start))
          (cond ((>= i end) #f)
                ((match (string-ref s i)) i)
                (else (loop (+ i 1)))))))

    (define (string-index-right s pred . rest)
      (let ((match (%char-match pred))
            (start (if (pair? rest) (car rest) 0))
            (end   (if (and (pair? rest) (pair? (cdr rest)))
                       (cadr rest) (string-length s))))
        (let loop ((i (- end 1)))
          (cond ((< i start) #f)
                ((match (string-ref s i)) i)
                (else (loop (- i 1)))))))

    ;; index of the first (last) char that does NOT satisfy the criterion —
    ;; the searches string-trim conceptually runs.
    (define (string-skip s pred . rest)
      (let ((match (%char-match pred)))
        (apply string-index s (lambda (c) (not (match c))) rest)))

    (define (string-skip-right s pred . rest)
      (let ((match (%char-match pred)))
        (apply string-index-right s (lambda (c) (not (match c))) rest)))

    (define (string-rindex s pred . rest)
      (apply string-index-right s pred rest))

    ;; Index of the first occurrence of `pat` in `s`, or #f.
    (define (string-contains s pat)
      (let ((n (string-length s)) (m (string-length pat)))
        (let loop ((i 0))
          (cond ((> (+ i m) n) #f)
                ((string=? pat (substring s i (+ i m))) i)
                (else (loop (+ i 1)))))))

    (define (string-count s pred)
      (let ((match (%char-match pred)))
        (let loop ((i 0) (n 0))
          (if (= i (string-length s))
              n
              (loop (+ i 1) (if (match (string-ref s i)) (+ n 1) n))))))

    ;; (string-join strings [delimiter [grammar]]) — infix is the default.
    (define (string-join strings . rest)
      (let ((delim (if (pair? rest) (car rest) \" \")))
        (if (null? strings)
            \"\"
            (let loop ((l (cdr strings)) (acc (car strings)))
              (if (null? l)
                  acc
                  (loop (cdr l) (string-append acc delim (car l))))))))

    ;; Split on a single character delimiter.  Adjacent delimiters produce
    ;; empty strings, which is what makes this the inverse of string-join;
    ;; string-tokenize is the variant that drops them.
    (define (string-split s ch)
      (let ((n (string-length s)))
        (let loop ((i 0) (start 0) (acc '()))
          (cond
            ((= i n) (reverse (cons (substring s start n) acc)))
            ((char=? (string-ref s i) ch)
             (loop (+ i 1) (+ i 1) (cons (substring s start i) acc)))
            (else (loop (+ i 1) start acc))))))

    (define (string-tokenize s . rest)
      (let ((pred (if (pair? rest)
                      (%char-match (car rest))
                      (lambda (c) (not (char-whitespace? c)))))
            (n (string-length s)))
        (let loop ((i 0) (start #f) (acc '()))
          (cond
            ((= i n) (reverse (if start (cons (substring s start n) acc) acc)))
            ((pred (string-ref s i))
             (loop (+ i 1) (or start i) acc))
            (start (loop (+ i 1) #f (cons (substring s start i) acc)))
            (else (loop (+ i 1) #f acc))))))

    (define (string-reverse s)
      (list->string (reverse (string->list s))))

    (define (string-concatenate strings)
      (let loop ((l strings) (acc \"\"))
        (if (null? l) acc (loop (cdr l) (string-append acc (car l))))))

    (define (string-fold kons knil s)
      (let loop ((i 0) (acc knil))
        (if (= i (string-length s))
            acc
            (loop (+ i 1) (kons (string-ref s i) acc)))))

    (define (string-fold-right kons knil s)
      (let loop ((i (- (string-length s) 1)) (acc knil))
        (if (< i 0) acc (loop (- i 1) (kons (string-ref s i) acc)))))

    (define (string-delete pred s)
      (let ((match (%char-match pred)))
        (list->string
          (let loop ((cs (string->list s)) (acc '()))
            (cond ((null? cs) (reverse acc))
                  ((match (car cs)) (loop (cdr cs) acc))
                  (else (loop (cdr cs) (cons (car cs) acc))))))))

    (define (string-filter pred s)
      (let ((match (%char-match pred)))
        (string-delete (lambda (c) (not (match c))) s)))

    ;; (string-replace s1 s2 start end) — s1 with [start,end) replaced by s2.
    (define (string-replace s1 s2 start end)
      (string-append (substring s1 0 start) s2
                     (substring s1 end (string-length s1))))

    ;; (string-unfold p f g seed [base [make-final]]) — the list unfold with
    ;; the result accumulated as characters onto `base`, and make-final
    ;; applied to the final seed for a suffix.
    (define (string-unfold p f g seed . rest)
      (let ((base       (if (pair? rest) (car rest) \"\"))
            (make-final (if (and (pair? rest) (pair? (cdr rest)))
                            (cadr rest)
                            (lambda (seed) \"\"))))
        (let loop ((seed seed) (acc '()))
          (if (p seed)
              (string-append base (list->string (reverse acc)) (make-final seed))
              (loop (g seed) (cons (f seed) acc))))))

    (define (string-unfold-right p f g seed . rest)
      (let ((base       (if (pair? rest) (car rest) \"\"))
            (make-final (if (and (pair? rest) (pair? (cdr rest)))
                            (cadr rest)
                            (lambda (seed) \"\"))))
        (let loop ((seed seed) (acc '()))
          (if (p seed)
              (string-append (make-final seed) (list->string acc) base)
              (loop (g seed) (cons (f seed) acc))))))

    (define (string-tabulate proc len)
      (let loop ((i (- len 1)) (acc '()))
        (if (< i 0)
            (list->string acc)
            (loop (- i 1) (cons (proc i) acc)))))

    ;; Upcase each character that follows a non-alphabetic one, downcase the
    ;; rest — the word model SRFI 13 specifies for casing, with alphabetic
    ;; runs as words.
    (define (string-titlecase s)
      (let loop ((cs (string->list s)) (in-word? #f) (acc '()))
        (if (null? cs)
            (list->string (reverse acc))
            (let ((c (car cs)))
              (if (char-alphabetic? c)
                  (loop (cdr cs) #t
                        (cons (if in-word? (char-downcase c) (char-upcase c)) acc))
                  (loop (cdr cs) #f (cons c acc)))))))))
")
       (cons '(srfi 23)
             ";;; SRFI 23 — Error reporting mechanism
;;;
;;; `error` is already in paal-initial-env with R7RS semantics, which subsume
;;; SRFI 23's.  This library exists to give the SRFI its import path.
(define-library (srfi 23)
  (export)
  (begin))
")
       (cons '(srfi 28)
             ";;; SRFI 28 — Basic Format Strings
;;;
;;; ~a display, ~s write, ~% newline, ~~ tilde.  SRFI 48 builds on this and is
;;; a separate file so importing 28 alone gets only what 28 specifies.
(define-library (srfi 28)
  (import (scheme base) (scheme write))
  (export format)
  (begin
    (define (format fmt . args)
      (let ((out (open-output-string)))
        (let loop ((i 0) (args args))
          (if (>= i (string-length fmt))
              (get-output-string out)
              (let ((c (string-ref fmt i)))
                (if (and (char=? c #\\~) (< (+ i 1) (string-length fmt)))
                    (let ((d (string-ref fmt (+ i 1))))
                      (cond
                        ((or (char=? d #\\a) (char=? d #\\A))
                         (display (car args) out) (loop (+ i 2) (cdr args)))
                        ((or (char=? d #\\s) (char=? d #\\S))
                         (write (car args) out) (loop (+ i 2) (cdr args)))
                        ((char=? d #\\%) (newline out) (loop (+ i 2) args))
                        ((char=? d #\\~) (write-char #\\~ out) (loop (+ i 2) args))
                        (else (error \"format: unknown directive\" d))))
                    (begin (write-char c out) (loop (+ i 1) args)))))))))) 
")
       (cons '(srfi 39)
             ";;; SRFI 39 — Parameter objects
;;;
;;; Both names are provided by the base environment: make-parameter by the
;;; paal-native cell-based implementation in globals, parameterize by the
;;; expander (syntax is not gated by imports).  This library re-exports the
;;; value so `(import (srfi 39))` grants it, and records the one SRFI 39
;;; behaviour beyond R7RS: `(p v)` sets the parameter's value through its
;;; converter, which both of paal's make-parameter implementations honour.
(define-library (srfi 39)
  (import (scheme base))
  (export make-parameter)
  (begin))
")
       (cons '(srfi 48)
             ";;; SRFI 48 — Intermediate Format Strings
;;;
;;; Adds ~d ~b ~o ~x (radix), ~c (character), ~w (write), ~y (pretty-print,
;;; here the same as write since paal has no pretty printer), ~? / ~k
;;; (recursive format), ~_ (space), ~t (tab), ~& (freshline), ~h (help) and
;;; the column-aligned numeric directive ~[w[,d]]F to SRFI 28's set —
;;; matching the directive set of kaappi's (srfi 48).
;;;
;;; Like SRFI 28's, `format` here takes the format string first.  SRFI 48 also
;;; allows a leading port or #f/#t argument; that form is supported.
(define-library (srfi 48)
  (import (scheme base) (scheme char) (scheme write))
  (export format)
  (begin
    (define (%pad-left s width)
      (let ((slen (string-length s)))
        (if (>= slen width)
            s
            (string-append (make-string (- width slen) #\\space) s))))

    ;; num printed with exactly `decimals` digits after the point, rounded.
    (define (%format-float num decimals)
      (let* ((neg (negative? num))
             (abs-num (abs num))
             (int-part (exact (truncate abs-num)))
             (frac (- abs-num int-part))
             (multiplier (expt 10 decimals))
             (frac-digits (exact (round (* frac multiplier))))
             (carry (if (>= frac-digits multiplier) 1 0))
             (frac-digits2 (if (>= frac-digits multiplier) 0 frac-digits))
             (int-str (number->string (+ int-part carry)))
             (frac-str (number->string frac-digits2))
             (frac-padded (if (< (string-length frac-str) decimals)
                              (string-append
                                (make-string (- decimals (string-length frac-str)) #\\0)
                                frac-str)
                              frac-str)))
        (string-append (if neg \"-\" \"\") int-str \".\" frac-padded)))

    ;; ~[w[,d]]F: obj right-aligned in `width` columns, numbers with `decimals`
    ;; fraction digits when given.  Strings and other objects just pad.
    (define (%format-fixed out obj width decimals)
      (cond
        ((string? obj)
         (display (%pad-left obj width) out))
        ((number? obj)
         (if decimals
             (display (%pad-left (%format-float (+ obj 0.0) decimals) width) out)
             (display (%pad-left (number->string obj) width) out)))
        (else
         (let ((p (open-output-string)))
           (display obj p)
           (display (%pad-left (get-output-string p) width) out)))))

    (define %format-help
      (string-append
        \"~a display  ~s write  ~w write  ~d decimal  ~x hex  ~o octal\"
        \"  ~b binary  ~c character  ~y pretty-print  ~? ~k indirection\"
        \"  ~[w[,d]]F fixed  ~% ~n newline  ~& freshline  ~t tab  ~_ space\"
        \"  ~~ tilde  ~h help\"))

    ;; The loop threads nl? — was the last character emitted a newline — so
    ;; ~& (freshline) can start a line only when not already at one.  After a
    ;; displayed argument the answer is taken as no, as kaappi's does.
    (define (%format-to out fmt args)
      (let loop ((i 0) (args args) (nl? #f))
        (if (>= i (string-length fmt))
            #t
            (let ((c (string-ref fmt i)))
              (if (and (char=? c #\\~) (< (+ i 1) (string-length fmt)))
                  (let ((d (char-downcase (string-ref fmt (+ i 1)))))
                    (cond
                      ((char=? d #\\a) (display (car args) out) (loop (+ i 2) (cdr args) #f))
                      ((char=? d #\\s) (write (car args) out) (loop (+ i 2) (cdr args) #f))
                      ((char=? d #\\w) (write (car args) out) (loop (+ i 2) (cdr args) #f))
                      ((char=? d #\\y) (write (car args) out) (loop (+ i 2) (cdr args) #f))
                      ((char=? d #\\d) (display (number->string (car args) 10) out)
                                      (loop (+ i 2) (cdr args) #f))
                      ((char=? d #\\b) (display (number->string (car args) 2) out)
                                      (loop (+ i 2) (cdr args) #f))
                      ((char=? d #\\o) (display (number->string (car args) 8) out)
                                      (loop (+ i 2) (cdr args) #f))
                      ((char=? d #\\x) (display (number->string (car args) 16) out)
                                      (loop (+ i 2) (cdr args) #f))
                      ((char=? d #\\c) (write-char (car args) out) (loop (+ i 2) (cdr args) #f))
                      ((or (char=? d #\\?) (char=? d #\\k))
                       (%format-to out (car args) (cadr args))
                       (loop (+ i 2) (cddr args) #f))
                      ((char=? d #\\%) (newline out) (loop (+ i 2) args #t))
                      ((char=? d #\\n) (newline out) (loop (+ i 2) args #t))
                      ((char=? d #\\&) (unless nl? (newline out)) (loop (+ i 2) args #t))
                      ((char=? d #\\_) (write-char #\\space out) (loop (+ i 2) args #f))
                      ((char=? d #\\t) (write-char #\\tab out) (loop (+ i 2) args #f))
                      ((char=? d #\\~) (write-char #\\~ out) (loop (+ i 2) args #f))
                      ((char=? d #\\h) (display %format-help out) (loop (+ i 2) args #f))
                      ((char-numeric? d)
                       (let parse ((j (+ i 1)) (width 0) (decs #f))
                         (if (>= j (string-length fmt))
                             (error \"format: incomplete ~F directive\" fmt)
                             (let ((ch (string-ref fmt j)))
                               (cond
                                 ((char-numeric? ch)
                                  (let ((digit (- (char->integer ch) (char->integer #\\0))))
                                    (if decs
                                        (parse (+ j 1) width (+ (* decs 10) digit))
                                        (parse (+ j 1) (+ (* width 10) digit) #f))))
                                 ((char=? ch #\\,)
                                  (parse (+ j 1) width 0))
                                 ((char=? (char-downcase ch) #\\f)
                                  (%format-fixed out (car args) width decs)
                                  (loop (+ j 1) (cdr args) #f))
                                 (else
                                  (error \"format: expected F after width\" ch)))))))
                      (else (error \"format: unknown directive\" d))))
                  (begin (write-char c out) (loop (+ i 1) args (char=? c #\\newline))))))))

    ;; (format fmt arg ...) -> string
    ;; (format #f fmt arg ...) -> string
    ;; (format #t fmt arg ...) -> writes to current output, returns unspecified
    ;; (format port fmt arg ...) -> writes to port
    (define (format first . rest)
      (cond
        ((string? first)
         (let ((out (open-output-string)))
           (%format-to out first rest)
           (get-output-string out)))
        ((eq? first #f)
         (let ((out (open-output-string)))
           (%format-to out (car rest) (cdr rest))
           (get-output-string out)))
        ((eq? first #t)
         (%format-to (current-output-port) (car rest) (cdr rest))
         (if #f #f))
        (else
         (%format-to first (car rest) (cdr rest))
         (if #f #f))))))
")
       (cons '(srfi 64)
             ";;; SRFI 64 — A Scheme API for test suites
;;;
;;; The commonly-used subset: the test forms, grouping, skip/expect-fail, and
;;; the result counters.  Enough to run a real suite and to eventually replace
;;; paal's dependency on `(kaappi test)`.
;;;
;;; The assertions are `syntax`, not procedures, because a test that raises
;;; must fail *that test* and let the run continue.  A procedural
;;; `(test-equal expected actual)` evaluates `actual` at the call site, so a
;;; raise escapes before the framework sees it and takes the rest of the group
;;; with it.  Thunking inside the macro is what makes a raise a failure rather
;;; than an abort — the same lesson `(kaappi test)` learned.
;;;
;;; Not implemented: test-apply, test-with-runner, custom runners, and the
;;; test-result-alist introspection beyond kind/name.

(define-library (srfi 64)
  (import (scheme base) (scheme write))
  (export
    test-begin test-end test-group test-group-with-cleanup
    test-assert test-eqv test-equal test-eq test-approximate
    test-error test-skip test-expect-fail
    test-runner-current test-runner-simple test-runner-null
    test-runner-pass-count test-runner-fail-count
    test-runner-xpass-count test-runner-xfail-count
    test-runner-skip-count test-runner-test-name
    test-exit)
  (begin

    ;; --- runner state -------------------------------------------------
    ;;
    ;; One implicit runner.  SRFI 64 allows several, but a second one has no
    ;; use here and would need a parameter object per counter.

    (define %pass 0)
    (define %fail 0)
    (define %xpass 0)
    (define %xfail 0)
    (define %skip 0)
    (define %group-stack '())
    (define %current-name \"\")
    ;; Predicates queued by test-skip / test-expect-fail, consumed by the next
    ;; test whose name they match.  SRFI 64 specifiers may be a name string, a
    ;; count, or a predicate; string and predicate are supported.
    (define %skip-specs '())
    (define %fail-specs '())

    (define (test-runner-current) 'srfi-64-implicit-runner)
    (define (test-runner-simple)  'srfi-64-implicit-runner)
    (define (test-runner-null)    'srfi-64-implicit-runner)
    (define (test-runner-pass-count . r)  %pass)
    (define (test-runner-fail-count . r)  %fail)
    (define (test-runner-xpass-count . r) %xpass)
    (define (test-runner-xfail-count . r) %xfail)
    (define (test-runner-skip-count . r)  %skip)
    (define (test-runner-test-name . r)   %current-name)

    (define (%indent)
      (let loop ((n (length %group-stack)))
        (when (> n 0) (display \"  \") (loop (- n 1)))))

    (define (test-begin name)
      (%indent)
      (display name) (newline)
      (set! %group-stack (cons name %group-stack)))

    (define (test-end . name)
      (unless (null? %group-stack)
        (set! %group-stack (cdr %group-stack))))

    ;; --- specifier matching -------------------------------------------

    (define (%matches? spec name)
      (cond ((string? spec) (and (string? name) (string=? spec name)))
            ((procedure? spec) (spec name))
            (else #f)))

    (define (%consume! specs name)
      ;; #t if any queued specifier matches; matching ones are removed, so a
      ;; specifier applies to one test, per SRFI 64.
      (let loop ((ss specs) (kept '()) (hit #f))
        (cond
          ((null? ss) (cons (reverse kept) hit))
          ((%matches? (car ss) name) (loop (cdr ss) kept #t))
          (else (loop (cdr ss) (cons (car ss) kept) hit)))))

    (define (test-skip spec)        (set! %skip-specs (cons spec %skip-specs)))
    (define (test-expect-fail spec) (set! %fail-specs (cons spec %fail-specs)))

    ;; --- the one place a result is recorded ---------------------------
    ;;
    ;; thunk returns #t for a pass.  It is called inside a guard, so a raise
    ;; is a failure of this test rather than the end of the run.

    (define (%run-test name thunk describe)
      (set! %current-name name)
      (let* ((sk (%consume! %skip-specs name))
             (xf (%consume! %fail-specs name)))
        (set! %skip-specs (car sk))
        (set! %fail-specs (car xf))
        (cond
          ((cdr sk)
           (set! %skip (+ %skip 1))
           (%indent) (display \"    skip: \") (display name) (newline))
          (else
           (let ((ok (guard (e (#t (cons #f e))) (cons (thunk) #f))))
             (let ((passed (car ok)) (raised (cdr ok)))
               (cond
                 ((and passed (cdr xf))
                  (set! %xpass (+ %xpass 1))
                  (%indent) (display \"    XPASS: \") (display name) (newline))
                 ((cdr xf)
                  (set! %xfail (+ %xfail 1))
                  (%indent) (display \"    xfail: \") (display name) (newline))
                 (passed
                  (set! %pass (+ %pass 1))
                  (%indent) (display \"    ok: \") (display name) (newline))
                 (else
                  (set! %fail (+ %fail 1))
                  (%indent) (display \"    FAIL: \") (display name) (newline)
                  (when raised
                    (%indent) (display \"      raised: \")
                    (display (if (error-object? raised)
                                 (error-object-message raised)
                                 raised))
                    (newline))
                  (when describe (describe))))))))))

    (define (%report-mismatch expected actual)
      (lambda ()
        (%indent) (display \"      expected: \") (write expected) (newline)
        (%indent) (display \"      actual:   \") (write actual) (newline)))

    ;; --- assertions ----------------------------------------------------
    ;;
    ;; Each thunks its expression, so a raise inside becomes a failed test
    ;; rather than an abort.  Every one accepts the optional leading name that
    ;; SRFI 64 allows.

    (define (%assert name thunk)
      (%run-test name (lambda () (and (thunk) #t)) #f))

    (define (%compare name same? expected-thunk actual-thunk)
      (let ((expected #f) (actual #f))
        (%run-test name
                   (lambda ()
                     (set! expected (expected-thunk))
                     (set! actual (actual-thunk))
                     (same? expected actual))
                   (lambda () ((%report-mismatch expected actual))))))

    (define-syntax test-assert
      (syntax-rules ()
        ((_ name expr) (%assert name (lambda () expr)))
        ((_ expr)      (%assert \"test-assert\" (lambda () expr)))))

    (define-syntax test-equal
      (syntax-rules ()
        ((_ name expected actual)
         (%compare name equal? (lambda () expected) (lambda () actual)))
        ((_ expected actual)
         (%compare \"test-equal\" equal? (lambda () expected) (lambda () actual)))))

    (define-syntax test-eqv
      (syntax-rules ()
        ((_ name expected actual)
         (%compare name eqv? (lambda () expected) (lambda () actual)))
        ((_ expected actual)
         (%compare \"test-eqv\" eqv? (lambda () expected) (lambda () actual)))))

    (define-syntax test-eq
      (syntax-rules ()
        ((_ name expected actual)
         (%compare name eq? (lambda () expected) (lambda () actual)))
        ((_ expected actual)
         (%compare \"test-eq\" eq? (lambda () expected) (lambda () actual)))))

    (define-syntax test-approximate
      (syntax-rules ()
        ((_ name expected actual err)
         (%compare name
                   (lambda (e a) (<= (- e err) a (+ e err)))
                   (lambda () expected) (lambda () actual)))
        ((_ expected actual err)
         (%compare \"test-approximate\"
                   (lambda (e a) (<= (- e err) a (+ e err)))
                   (lambda () expected) (lambda () actual)))))

    ;; Passes when the expression raises.  The error-type argument is accepted
    ;; and ignored: paal has no condition hierarchy to match against.
    (define-syntax test-error
      (syntax-rules ()
        ((_ name etype expr)
         (%run-test name (lambda () (guard (e (#t #t)) expr #f)) #f))
        ((_ name expr)
         (%run-test name (lambda () (guard (e (#t #t)) expr #f)) #f))
        ((_ expr)
         (%run-test \"test-error\" (lambda () (guard (e (#t #t)) expr #f)) #f))))

    (define-syntax test-group
      (syntax-rules ()
        ((_ name body ...)
         (begin (test-begin name) body ... (test-end name)))))

    ;; The cleanup form runs whether or not the body raised, which is the
    ;; whole point of this variant.
    (define-syntax test-group-with-cleanup
      (syntax-rules ()
        ((_ name body ... cleanup)
         (begin
           (test-begin name)
           (guard (e (#t cleanup (test-end name) (raise e)))
             body ...)
           cleanup
           (test-end name)))))

    ;; Not in SRFI 64, but every suite needs it and paal's runner has one.
    ;; Exits 1 if anything failed or unexpectedly passed.
    (define (test-exit)
      (newline)
      (display (+ %pass %fail %xpass %xfail %skip))
      (display \" tests: \")
      (display %pass) (display \" passed\")
      (when (> %fail 0)  (display \", \") (display %fail)  (display \" failed\"))
      (when (> %xfail 0) (display \", \") (display %xfail) (display \" expected failures\"))
      (when (> %xpass 0) (display \", \") (display %xpass) (display \" unexpected passes\"))
      (when (> %skip 0)  (display \", \") (display %skip)  (display \" skipped\"))
      (newline)
      (if (or (> %fail 0) (> %xpass 0)) 1 0))))
")
       (cons '(srfi 69)
             ";;; SRFI 69 — Basic Hash Tables
;;;
;;; Separate chaining over a vector of buckets, grown when the load factor
;;; passes 0.75.  The table is a tagged vector rather than a record, matching
;;; the convention the rest of paal uses for values that may cross the
;;; HOST/self-hosted boundary: a record type's identity is per compiled copy,
;;; while an interned symbol is the same object in both.
;;;
;;; hash for a string or symbol is the usual multiply-and-add over the
;;; characters; anything else falls back to a constant, which is correct but
;;; degrades that key's lookups to a linear scan of its bucket.  Numbers get an
;;; exact-integer path so numeric keys, the other common case, spread properly.

(define-library (srfi 69)
  (import (scheme base) (scheme char))
  (export
    make-hash-table hash-table? hash-table-set! hash-table-ref
    hash-table-ref/default hash-table-delete! hash-table-exists?
    hash-table-size hash-table-keys hash-table-values hash-table-walk
    hash-table-fold hash-table->alist alist->hash-table
    hash-table-update! hash-table-update!/default hash-table-copy
    hash-table-clear! hash-table-merge!
    hash-table-equivalence-function hash-table-hash-function
    hash string-hash string-ci-hash hash-by-identity)
  (begin

    (define %ht-tag '%srfi69-hash-table)
    (define %initial-buckets 16)

    ;; #(tag buckets count equal-proc hash-proc)
    (define (%buckets t)   (vector-ref t 1))
    (define (%count t)     (vector-ref t 2))
    (define (%equiv t)     (vector-ref t 3))
    (define (%hashfn t)    (vector-ref t 4))
    (define (%set-buckets! t v) (vector-set! t 1 v))
    (define (%set-count! t n)   (vector-set! t 2 n))

    (define (hash-table? x)
      (and (vector? x) (= (vector-length x) 5) (eq? (vector-ref x 0) %ht-tag)))

    ;; (make-hash-table [equal [hash]])
    (define (make-hash-table . rest)
      (let ((eq-proc (if (pair? rest) (car rest) equal?))
            (h-proc  (if (and (pair? rest) (pair? (cdr rest)))
                         (cadr rest)
                         hash)))
        (vector %ht-tag (make-vector %initial-buckets '()) 0 eq-proc h-proc)))

    ;; --- hashing -----------------------------------------------------

    (define (string-hash s . rest)
      (let ((bound (if (pair? rest) (car rest) 0)))
        (let loop ((i 0) (h 5381))
          (if (= i (string-length s))
              (if (> bound 0) (modulo h bound) h)
              (loop (+ i 1)
                    (modulo (+ (* h 33) (char->integer (string-ref s i)))
                            1000000007))))))

    (define (string-ci-hash s . rest)
      (apply string-hash (string-foldcase s) rest))

    (define (hash obj . rest)
      (let ((bound (if (pair? rest) (car rest) 0))
            (h (cond
                 ((string? obj) (string-hash obj))
                 ((symbol? obj) (string-hash (symbol->string obj)))
                 ((char? obj)   (char->integer obj))
                 ((and (number? obj) (exact? obj) (integer? obj)) (abs obj))
                 ((number? obj) (abs (exact (truncate obj))))
                 ((boolean? obj) (if obj 1 0))
                 ((null? obj) 2)
                 ((pair? obj) 3)
                 ((vector? obj) (vector-length obj))
                 (else 0))))
        (if (> bound 0) (modulo h bound) h)))

    (define (hash-by-identity obj . rest) (apply hash obj rest))

    (define (%index t key)
      (modulo ((%hashfn t) key) (vector-length (%buckets t))))

    ;; --- core operations ---------------------------------------------

    (define (%assoc-in t key bucket)
      (let ((same? (%equiv t)))
        (let loop ((b bucket))
          (cond ((null? b) #f)
                ((same? key (caar b)) (car b))
                (else (loop (cdr b)))))))

    (define (hash-table-set! t key value)
      (let* ((i   (%index t key))
             (bkt (vector-ref (%buckets t) i))
             (hit (%assoc-in t key bkt)))
        (if hit
            (set-cdr! hit value)
            (begin
              (vector-set! (%buckets t) i (cons (cons key value) bkt))
              (%set-count! t (+ (%count t) 1))
              (when (> (* 4 (%count t)) (* 3 (vector-length (%buckets t))))
                (%grow! t))))))

    ;; Rehash into a table twice the size.  Entries are re-consed rather than
    ;; moved so the old buckets can be dropped whole.
    (define (%grow! t)
      (let* ((old (%buckets t))
             (new (make-vector (* 2 (vector-length old)) '())))
        (%set-buckets! t new)
        (let loop ((i 0))
          (when (< i (vector-length old))
            (for-each
              (lambda (entry)
                (let ((j (%index t (car entry))))
                  (vector-set! new j (cons entry (vector-ref new j)))))
              (vector-ref old i))
            (loop (+ i 1))))))

    ;; (hash-table-ref t key [failure [success]])
    (define (hash-table-ref t key . rest)
      (let ((hit (%assoc-in t key (vector-ref (%buckets t) (%index t key)))))
        (cond
          (hit (if (and (pair? rest) (pair? (cdr rest)))
                   ((cadr rest) (cdr hit))
                   (cdr hit)))
          ((pair? rest) ((car rest)))
          (else (error \"hash-table-ref: no such key\" key)))))

    (define (hash-table-ref/default t key default)
      (let ((hit (%assoc-in t key (vector-ref (%buckets t) (%index t key)))))
        (if hit (cdr hit) default)))

    (define (hash-table-exists? t key)
      (and (%assoc-in t key (vector-ref (%buckets t) (%index t key))) #t))

    (define (hash-table-delete! t key)
      (let* ((i     (%index t key))
             (bkt   (vector-ref (%buckets t) i))
             (same? (%equiv t))
             (kept  (let loop ((b bkt) (acc '()) (found #f))
                      (cond
                        ((null? b) (cons (reverse acc) found))
                        ((same? key (caar b)) (loop (cdr b) acc #t))
                        (else (loop (cdr b) (cons (car b) acc) found))))))
        (vector-set! (%buckets t) i (car kept))
        (when (cdr kept) (%set-count! t (- (%count t) 1)))))

    (define (hash-table-size t) (%count t))

    (define (hash-table-walk t proc)
      (let loop ((i 0))
        (when (< i (vector-length (%buckets t)))
          (for-each (lambda (e) (proc (car e) (cdr e)))
                    (vector-ref (%buckets t) i))
          (loop (+ i 1)))))

    (define (hash-table-fold t kons knil)
      (let ((acc knil))
        (hash-table-walk t (lambda (k v) (set! acc (kons k v acc))))
        acc))

    (define (hash-table-keys t)
      (hash-table-fold t (lambda (k v acc) (cons k acc)) '()))

    (define (hash-table-values t)
      (hash-table-fold t (lambda (k v acc) (cons v acc)) '()))

    (define (hash-table->alist t)
      (hash-table-fold t (lambda (k v acc) (cons (cons k v) acc)) '()))

    ;; Earlier entries win, per SRFI 69.
    (define (alist->hash-table alist . rest)
      (let ((t (apply make-hash-table rest)))
        (for-each (lambda (p)
                    (unless (hash-table-exists? t (car p))
                      (hash-table-set! t (car p) (cdr p))))
                  alist)
        t))

    (define (hash-table-update! t key proc . rest)
      (let ((current
             (if (pair? rest)
                 (hash-table-ref t key (car rest))
                 (hash-table-ref t key))))
        (hash-table-set! t key (proc current))))

    (define (hash-table-update!/default t key proc default)
      (hash-table-set! t key (proc (hash-table-ref/default t key default))))

    (define (hash-table-copy t)
      (let ((out (vector %ht-tag
                         (make-vector (vector-length (%buckets t)) '())
                         0 (%equiv t) (%hashfn t))))
        (hash-table-walk t (lambda (k v) (hash-table-set! out k v)))
        out))

    (define (hash-table-clear! t)
      (%set-buckets! t (make-vector %initial-buckets '()))
      (%set-count! t 0))

    ;; The two constructor arguments, read back off the representation.
    (define (hash-table-equivalence-function t) (%equiv t))
    (define (hash-table-hash-function t)        (%hashfn t))

    ;; src's entries into dst, src winning on collision; returns dst.
    (define (hash-table-merge! dst src)
      (hash-table-walk src (lambda (k v) (hash-table-set! dst k v)))
      dst)))
")
       (cons '(srfi 133)
             ";;; SRFI 133 — Vector Library (R7RS-compatible)
;;;
;;; The commonly-used subset.  `vector-map`, `vector-for-each`, `vector-fill!`,
;;; `vector-copy`, `vector-copy!` and `vector-append` are R7RS names paal
;;; already binds with compatible semantics, so they are not redefined here —
;;; importing this alongside `(scheme base)` would otherwise bind one name two
;;; ways, which R7RS 5.2 makes an error.
;;;
;;; Not implemented: the multi-vector forms of vector-fold and friends beyond
;;; two vectors, vector-unfold-right's full generality, and the `!` variants
;;; that SRFI 133 marks as linear-update.

(define-library (srfi 133)
  (import (scheme base))
  (export
    vector-empty? vector= vector-count vector-index vector-index-right
    vector-skip vector-skip-right
    vector-fold vector-fold-right vector-reduce vector-reduce-right
    vector-unfold vector-unfold-right vector-unfold! vector-unfold-right!
    vector-tabulate vector-cumulate
    vector-binary-search vector-any vector-every
    vector-swap! vector-reverse! vector-reverse-copy vector-reverse-copy!
    vector-map!
    vector-concatenate vector-append-subvectors vector->list* vector-partition
    vector-find vector-take vector-drop
    reverse-vector->list reverse-list->vector)
  (begin

    (define (vector-empty? v) (= (vector-length v) 0))

    (define (vector= elt= . vs)
      (cond
        ((null? vs) #t)
        ((null? (cdr vs)) #t)
        (else
         (let outer ((a (car vs)) (rest (cdr vs)))
           (if (null? rest)
               #t
               (let ((b (car rest)))
                 (and (= (vector-length a) (vector-length b))
                      (let inner ((i 0))
                        (cond ((= i (vector-length a)) #t)
                              ((elt= (vector-ref a i) (vector-ref b i))
                               (inner (+ i 1)))
                              (else #f)))
                      (outer b (cdr rest)))))))))

    (define (vector-count pred v)
      (let loop ((i 0) (n 0))
        (if (= i (vector-length v))
            n
            (loop (+ i 1) (if (pred (vector-ref v i)) (+ n 1) n)))))

    (define (vector-index pred v)
      (let loop ((i 0))
        (cond ((= i (vector-length v)) #f)
              ((pred (vector-ref v i)) i)
              (else (loop (+ i 1))))))

    (define (vector-skip pred v)
      (vector-index (lambda (x) (not (pred x))) v))

    (define (vector-index-right pred v)
      (let loop ((i (- (vector-length v) 1)))
        (cond ((< i 0) #f)
              ((pred (vector-ref v i)) i)
              (else (loop (- i 1))))))

    (define (vector-skip-right pred v)
      (vector-index-right (lambda (x) (not (pred x))) v))

    (define (vector-find pred v)
      (let ((i (vector-index pred v)))
        (and i (vector-ref v i))))

    ;; (vector-fold kons knil v) — kons receives the accumulator first, per
    ;; SRFI 133, which is the opposite order from SRFI 1's fold.
    (define (vector-fold kons knil v)
      (let loop ((i 0) (acc knil))
        (if (= i (vector-length v))
            acc
            (loop (+ i 1) (kons acc (vector-ref v i))))))

    (define (vector-fold-right kons knil v)
      (let loop ((i (- (vector-length v) 1)) (acc knil))
        (if (< i 0)
            acc
            (loop (- i 1) (kons acc (vector-ref v i))))))

    (define (vector-reduce f knil v)
      (if (vector-empty? v)
          knil
          (let loop ((i 1) (acc (vector-ref v 0)))
            (if (= i (vector-length v))
                acc
                (loop (+ i 1) (f acc (vector-ref v i)))))))

    (define (vector-reduce-right f knil v)
      (if (vector-empty? v)
          knil
          (let ((n (vector-length v)))
            (let loop ((i (- n 2)) (acc (vector-ref v (- n 1))))
              (if (< i 0)
                  acc
                  (loop (- i 1) (f acc (vector-ref v i))))))))

    ;; (vector-unfold f length seed) — f returns the element for each index.
    (define (vector-unfold f len seed)
      (let ((v (make-vector len)))
        (let loop ((i 0) (seed seed))
          (if (= i len)
              v
              (call-with-values (lambda () (f i seed))
                (lambda (elt next)
                  (vector-set! v i elt)
                  (loop (+ i 1) next)))))))

    (define (vector-tabulate proc len)
      (let ((v (make-vector len)))
        (let loop ((i 0))
          (if (= i len)
              v
              (begin (vector-set! v i (proc i)) (loop (+ i 1)))))))

    ;; The unfold family, in the file's single-seed shape.  f returns
    ;; (values elt next-seed); the ! variants fill [start,end) of an
    ;; existing vector, the -right ones fill highest index first.
    (define (vector-unfold-right f len seed)
      (let ((v (make-vector len)))
        (let loop ((i (- len 1)) (seed seed))
          (if (< i 0)
              v
              (call-with-values (lambda () (f i seed))
                (lambda (elt next)
                  (vector-set! v i elt)
                  (loop (- i 1) next)))))))

    (define (vector-unfold! f v start end seed)
      (let loop ((i start) (seed seed))
        (if (>= i end)
            v
            (call-with-values (lambda () (f i seed))
              (lambda (elt next)
                (vector-set! v i elt)
                (loop (+ i 1) next))))))

    (define (vector-unfold-right! f v start end seed)
      (let loop ((i (- end 1)) (seed seed))
        (if (< i start)
            v
            (call-with-values (lambda () (f i seed))
              (lambda (elt next)
                (vector-set! v i elt)
                (loop (- i 1) next))))))

    ;; (vector-cumulate f knil v) — v's running fold: element i of the result
    ;; is the fold of v's first i+1 elements.
    (define (vector-cumulate f knil v)
      (let* ((len (vector-length v))
             (out (make-vector len)))
        (let loop ((i 0) (acc knil))
          (if (= i len)
              out
              (let ((acc (f acc (vector-ref v i))))
                (vector-set! out i acc)
                (loop (+ i 1) acc))))))

    ;; cmp returns negative, zero or positive.
    (define (vector-binary-search v value cmp)
      (let loop ((lo 0) (hi (- (vector-length v) 1)))
        (if (> lo hi)
            #f
            (let* ((mid (quotient (+ lo hi) 2))
                   (c   (cmp (vector-ref v mid) value)))
              (cond ((= c 0) mid)
                    ((< c 0) (loop (+ mid 1) hi))
                    (else    (loop lo (- mid 1))))))))

    (define (vector-any pred v)
      (let loop ((i 0))
        (cond ((= i (vector-length v)) #f)
              ((pred (vector-ref v i)))
              (else (loop (+ i 1))))))

    (define (vector-every pred v)
      (let loop ((i 0) (last #t))
        (cond ((= i (vector-length v)) last)
              ((pred (vector-ref v i)) => (lambda (r) (loop (+ i 1) r)))
              (else #f))))

    (define (vector-swap! v i j)
      (let ((tmp (vector-ref v i)))
        (vector-set! v i (vector-ref v j))
        (vector-set! v j tmp)))

    (define (vector-reverse! v)
      (let loop ((i 0) (j (- (vector-length v) 1)))
        (if (< i j)
            (begin (vector-swap! v i j) (loop (+ i 1) (- j 1)))
            v)))

    (define (vector-reverse-copy v)
      (let* ((n (vector-length v)) (out (make-vector n)))
        (let loop ((i 0))
          (if (= i n)
              out
              (begin (vector-set! out i (vector-ref v (- n 1 i)))
                     (loop (+ i 1)))))))

    ;; (vector-reverse-copy! to at from [start [end]]) — from's [start,end)
    ;; into to at `at`, reversed.  Reads before writes via an intermediate
    ;; copy, so to and from may be the same vector with overlapping ranges.
    (define (vector-reverse-copy! to at from . rest)
      (let* ((start (if (pair? rest) (car rest) 0))
             (end   (if (and (pair? rest) (pair? (cdr rest)))
                        (cadr rest) (vector-length from)))
             (n     (- end start))
             (tmp   (make-vector n)))
        (let read ((i 0))
          (when (< i n)
            (vector-set! tmp i (vector-ref from (+ start i)))
            (read (+ i 1))))
        (let write ((i 0))
          (if (= i n)
              to
              (begin
                (vector-set! to (+ at i) (vector-ref tmp (- n 1 i)))
                (write (+ i 1)))))))

    ;; (vector-map! f v ...) — like vector-map, writing into the first
    ;; vector; over the shortest length when given several.
    (define (vector-map! f v . rest)
      (let ((len (let loop ((vs rest) (n (vector-length v)))
                   (if (null? vs)
                       n
                       (loop (cdr vs) (min n (vector-length (car vs))))))))
        (let loop ((i 0))
          (if (= i len)
              v
              (begin
                (vector-set! v i
                  (apply f (vector-ref v i)
                           (map (lambda (u) (vector-ref u i)) rest)))
                (loop (+ i 1)))))))

    (define (vector-concatenate vs)
      (let* ((total (let loop ((l vs) (n 0))
                      (if (null? l) n (loop (cdr l) (+ n (vector-length (car l)))))))
             (out   (make-vector total)))
        (let loop ((l vs) (at 0))
          (if (null? l)
              out
              (let ((v (car l)))
                (let copy ((i 0))
                  (if (= i (vector-length v))
                      (loop (cdr l) (+ at (vector-length v)))
                      (begin (vector-set! out (+ at i) (vector-ref v i))
                             (copy (+ i 1))))))))))

    (define (vector->list* v start end)
      (let loop ((i (- end 1)) (acc '()))
        (if (< i start) acc (loop (- i 1) (cons (vector-ref v i) acc)))))

    (define (vector-take v n) (vector-copy v 0 n))
    (define (vector-drop v n) (vector-copy v n (vector-length v)))

    ;; Returns the reordered vector and the count of elements satisfying pred.
    (define (vector-partition pred v)
      (let* ((n   (vector-length v))
             (out (make-vector n))
             (cnt 0))
        (let loop ((i 0) (at 0))
          (if (= i n)
              (set! cnt at)
              (if (pred (vector-ref v i))
                  (begin (vector-set! out at (vector-ref v i))
                         (loop (+ i 1) (+ at 1)))
                  (loop (+ i 1) at))))
        (let loop ((i 0) (at cnt))
          (if (= i n)
              (values out cnt)
              (if (pred (vector-ref v i))
                  (loop (+ i 1) at)
                  (begin (vector-set! out at (vector-ref v i))
                         (loop (+ i 1) (+ at 1))))))))

    ;; (vector-append-subvectors v1 s1 e1 v2 s2 e2 ...) — the named ranges
    ;; appended into one fresh vector.
    (define (vector-append-subvectors . args)
      (let* ((total (let loop ((a args) (n 0))
                      (if (null? a)
                          n
                          (loop (cdddr a) (+ n (- (caddr a) (cadr a)))))))
             (out   (make-vector total)))
        (let loop ((a args) (at 0))
          (if (null? a)
              out
              (let ((v (car a)) (start (cadr a)) (end (caddr a)))
                (let copy ((i start) (at at))
                  (if (= i end)
                      (loop (cdddr a) at)
                      (begin (vector-set! out at (vector-ref v i))
                             (copy (+ i 1) (+ at 1))))))))))

    (define (reverse-vector->list v . rest)
      (let ((start (if (pair? rest) (car rest) 0))
            (end   (if (and (pair? rest) (pair? (cdr rest)))
                       (cadr rest) (vector-length v))))
        (let loop ((i start) (acc '()))
          (if (= i end)
              acc
              (loop (+ i 1) (cons (vector-ref v i) acc))))))

    (define (reverse-list->vector lst)
      (let* ((n   (length lst))
             (out (make-vector n)))
        (let loop ((l lst) (i (- n 1)))
          (if (null? l)
              out
              (begin (vector-set! out i (car l))
                     (loop (cdr l) (- i 1)))))))))
")))
    ;; END GENERATED

    ;; Source text for a bundled library, or #f.
    (define (paal-embedded-source name)
      (let ((hit (assoc name %paal-embedded)))
        (and hit (cdr hit))))))
