;;; Print a replacement tests/srfi/paal-srfi-expected.sld from live runs.
;;; Redirect the output over that file and READ THE DIFF — the diff is the
;;; evidence a change did what it claimed.  Skip entries are hand-curated
;;; in paal-srfi-skip.sld and are not regenerated here.

(import (scheme base)
        (scheme write)
        (srfi 1)
        (srfi 170)
        (paal-srfi-driver)
        (paal-srfi-skip))

(define (scm-file? name)
  (let ((n (string-length name)))
    (and (> n 4) (string=? (substring name (- n 4) n) ".scm"))))

(define (sort-strings ls)
  (if (or (null? ls) (null? (cdr ls)))
      ls
      (let ((pivot (car ls))
            (rest  (cdr ls)))
        (append
          (sort-strings (filter (lambda (s) (string<? s pivot)) rest))
          (list pivot)
          (sort-strings (remove (lambda (s) (string<? s pivot)) rest))))))

(define files
  (sort-strings (filter scm-file? (directory-files "tests/srfi/vendor"))))

;; Collect first, print after: the vendored suites write progress and
;; failure lines to stdout while they run, and interleaving them into the
;; generated library would corrupt it.  With every run finished, the block
;; below is contiguous and the Makefile's sed can carve it out.
(define verdicts
  (let loop ((fs files) (acc '()))
    (cond
      ((null? fs) (reverse acc))
      ((assoc (car fs) skip-files) (loop (cdr fs) acc))
      (else
       (loop (cdr fs)
             (cons (cons (car fs)
                         (run-srfi-file
                           (string-append "tests/srfi/vendor/" (car fs))))
                   acc))))))

(display ";;; Generated by `make srfi-baseline`.  Do not hand-edit -- regenerate.")
(newline)
(display ";;; See tests/srfi/README.md.  Skips live in paal-srfi-skip.sld.")
(newline)
(newline)
(display "(define-library (paal-srfi-expected)")
(newline)
(display "  (export expected-verdicts)")
(newline)
(display "  (begin")
(newline)
(display "    ;; (file verdict) per vendored test file, in name order; a")
(newline)
(display "    ;; fail line carries the reason as a trailing comment.")
(newline)
(display "    (define expected-verdicts")
(newline)
(display "      '(")
(newline)
(for-each
  (lambda (entry)
    (let ((f (car entry)) (v (cdr entry)))
      (display "        (\"") (display f) (display "\" ")
      (display (if (eq? v 'pass) "pass" "fail"))
      (display ")")
      (unless (eq? v 'pass)
        (display " ; ") (display (cadr v)))
      (newline)))
  verdicts)
(display "        ))))")
(newline)
