;;; Generated by `make srfi-baseline`.  Do not hand-edit -- regenerate.
;;; See tests/srfi/README.md.  Skips live in paal-srfi-skip.sld.

(define-library (paal-srfi-expected)
  (export expected-verdicts)
  (begin
    ;; (file verdict) per vendored test file, in name order; a
    ;; fail line carries the reason as a trailing comment.
    (define expected-verdicts
      '(
        ("srfi-258.scm" pass)
        ("srfi-27-unit.scm" pass)
        ("srfi1-ext.scm" pass)
        ("srfi1.scm" pass)
        ("srfi113-audit.scm" pass)
        ("srfi113.scm" pass)
        ("srfi117.scm" pass)
        ("srfi125.scm" pass)
        ("srfi128.scm" pass)
        ("srfi13-charset.scm" pass)
        ("srfi13-ext.scm" pass)
        ("srfi13-startend.scm" pass)
        ("srfi132.scm" pass)
        ("srfi133-ext.scm" pass)
        ("srfi141.scm" pass)
        ("srfi151.scm" pass)
        ("srfi158.scm" pass)
        ("srfi2.scm" pass)
        ("srfi23.scm" pass)
        ("srfi26.scm" pass)
        ("srfi260.scm" pass)
        ("srfi27-audit.scm" fail) ; exit 1
        ("srfi27-state.scm" pass)
        ("srfi35-audit.scm" fail) ; exit 1
        ("srfi35.scm" pass)
        ("srfi39.scm" pass)
        ("srfi41.scm" fail) ; exit 1
        ("srfi42.scm" fail) ; syntax-rules: no matching pattern (%gref%%srfi%42%%do-ec %h-%ec-stop-6089 (nested (:range i 2) (:range j 2)) (%core%set!…
        ("srfi48.scm" pass)
        ("srfi60.scm" pass)
        ("srfi64.scm" pass)
        ("srfi69-ext.scm" pass)
        ("srfi69.scm" pass)
        ("srfi78.scm" pass)
        ("srfi9.scm" fail) ; exit 1
        ("srfi95.scm" pass)
        ))))
